<?php
/**
 * Contact form submission handler
 * My Invest Immobilier
 *
 * Receives POST from [contact-form] shortcodes rendered in public pages.
 */

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/db.php';

$siteUrl = rtrim($config['SITE_URL'] ?? '', '/');

// Detect AJAX request (fetch/XMLHttpRequest sets this header)
$isAjax = !empty($_SERVER['HTTP_X_REQUESTED_WITH'])
    && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';

/**
 * Send a JSON response and exit (for AJAX calls).
 */
function cfJsonResponse(array $data, int $statusCode = 200): never
{
    http_response_code($statusCode);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_UNESCAPED_UNICODE);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => 'Méthode non autorisée.'], 405);
    }
    header('Location: ' . $siteUrl . '/');
    exit;
}

$formId = isset($_POST['form_id']) ? (int)$_POST['form_id'] : 0;
if ($formId <= 0) {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => 'Formulaire invalide.'], 400);
    }
    http_response_code(400);
    exit('Formulaire invalide.');
}

// Validate CSRF token (must match the one generated by renderContactFormHtml)
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
$csrfKey      = 'csrf_contact_form_' . $formId;
$csrfReceived = $_POST['csrf_token'] ?? '';
$csrfExpected = $_SESSION[$csrfKey] ?? '';
if (!$csrfExpected || !hash_equals($csrfExpected, $csrfReceived)) {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => 'Jeton de sécurité invalide. Veuillez recharger la page et réessayer.', 'reload' => true], 403);
    }
    http_response_code(403);
    exit('Jeton CSRF invalide. Veuillez recharger la page et réessayer.');
}
// Regenerate token after successful validation to prevent reuse
$_SESSION[$csrfKey] = bin2hex(random_bytes(16));
$newCsrfToken = $_SESSION[$csrfKey];

// Fetch form configuration
try {
    $stmt = $pdo->prepare("SELECT * FROM contact_forms WHERE id = ? AND actif = 1 LIMIT 1");
    $stmt->execute([$formId]);
    $form = $stmt->fetch(PDO::FETCH_ASSOC);
} catch (Exception $e) {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => 'Erreur serveur.'], 500);
    }
    http_response_code(500);
    exit('Erreur serveur.');
}

if (!$form) {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => 'Formulaire introuvable.'], 404);
    }
    http_response_code(404);
    exit('Formulaire introuvable.');
}

// Fetch fields for validation
try {
    $stmtF = $pdo->prepare("SELECT * FROM contact_form_fields WHERE form_id = ? ORDER BY ordre ASC, id ASC");
    $stmtF->execute([$formId]);
    $fields = $stmtF->fetchAll(PDO::FETCH_ASSOC);
} catch (Exception $e) {
    $fields = [];
}

// ── reCAPTCHA validation ──────────────────────────────────────────────────────
$hasRcField = false;
foreach ($fields as $field) {
    if ($field['type_champ'] === 'recaptcha') {
        $hasRcField = true;
        break;
    }
}

if ($hasRcField) {
    // Load global reCAPTCHA settings
    $rcEnabled   = false;
    $rcType      = 'v2';
    $rcSecretKey = '';
    $rcMinScore  = 0.5;
    try {
        $stmtRc = $pdo->prepare("SELECT cle, valeur FROM parametres WHERE groupe = 'recaptcha'");
        $stmtRc->execute();
        foreach ($stmtRc->fetchAll(PDO::FETCH_ASSOC) as $row) {
            switch ($row['cle']) {
                case 'recaptcha_enabled':
                    $rcEnabled = ($row['valeur'] === '1' || $row['valeur'] === 'true');
                    break;
                case 'recaptcha_type':
                    $rcType = $row['valeur'];
                    break;
                case 'recaptcha_secret_key':
                    $rcSecretKey = $row['valeur'];
                    break;
                case 'recaptcha_min_score':
                    $rcMinScore = (float)$row['valeur'];
                    break;
            }
        }
    } catch (Exception $e) { /* ignore */ }

    if ($rcEnabled && $rcSecretKey !== '') {
        $rcResponse = trim($_POST['recaptcha_response'] ?? '');
        if ($rcResponse === '' && $rcType === 'v2') {
            // For V2, the response is in g-recaptcha-response
            $rcResponse = trim($_POST['g-recaptcha-response'] ?? '');
        }
        if ($rcResponse === '') {
            if ($isAjax) {
                cfJsonResponse(['success' => false, 'error' => 'Vérification anti-robot requise.', 'csrf_token' => $newCsrfToken]);
            }
            $ref = $_SERVER['HTTP_REFERER'] ?? ($siteUrl . '/');
            $sep = strpos($ref, '?') !== false ? '&' : '?';
            header('Location: ' . $ref . $sep . 'cf_error=' . urlencode('Vérification anti-robot requise.') . '&cf_form=' . $formId);
            exit;
        }

        $verifyData = [
            'secret'   => $rcSecretKey,
            'response' => $rcResponse,
            'remoteip' => $_SERVER['REMOTE_ADDR'] ?? '',
        ];
        $opts = [
            'http' => [
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($verifyData),
                'timeout' => 5,
            ],
        ];
        $verifyResult = file_get_contents(
            'https://www.google.com/recaptcha/api/siteverify',
            false,
            stream_context_create($opts)
        );
        if ($verifyResult === false) {
            error_log('contact-form-submit.php reCAPTCHA API unreachable for form ' . $formId);
            // Treat API failure as verification failure to remain secure
            if ($isAjax) {
                cfJsonResponse(['success' => false, 'error' => 'Vérification anti-robot temporairement indisponible. Veuillez réessayer.', 'csrf_token' => $newCsrfToken]);
            }
            $ref = $_SERVER['HTTP_REFERER'] ?? ($siteUrl . '/');
            $sep = strpos($ref, '?') !== false ? '&' : '?';
            header('Location: ' . $ref . $sep . 'cf_error=' . urlencode('Vérification anti-robot temporairement indisponible. Veuillez réessayer.') . '&cf_form=' . $formId);
            exit;
        }
        $rcResult = json_decode($verifyResult);

        $rcOk = $rcResult && $rcResult->success;
        if ($rcOk && $rcType === 'v3' && isset($rcResult->score)) {
            $rcOk = $rcResult->score >= $rcMinScore;
        }

        if (!$rcOk) {
            error_log('contact-form-submit.php reCAPTCHA failed for form ' . $formId);
            if ($isAjax) {
                cfJsonResponse(['success' => false, 'error' => 'Vérification anti-robot échouée. Veuillez réessayer.', 'csrf_token' => $newCsrfToken]);
            }
            $ref = $_SERVER['HTTP_REFERER'] ?? ($siteUrl . '/');
            $sep = strpos($ref, '?') !== false ? '&' : '?';
            header('Location: ' . $ref . $sep . 'cf_error=' . urlencode('Vérification anti-robot échouée. Veuillez réessayer.') . '&cf_form=' . $formId);
            exit;
        }
    }
}

// Build data array and validate required fields
$donnees = [];
$errors  = [];
foreach ($fields as $field) {
    if ($field['type_champ'] === 'recaptcha') {
        continue;
    }
    $nom   = $field['nom_champ'];
    $value = isset($_POST[$nom]) ? $_POST[$nom] : '';
    if (is_array($value)) {
        $value = array_map('strip_tags', $value);
    } else {
        $value = strip_tags(trim($value));
    }
    if ($field['requis'] && ($value === '' || $value === [])) {
        $errors[] = htmlspecialchars($field['label']) . ' est obligatoire.';
    }
    $donnees[$nom] = $value;
}

// Vérification anti-liens dans les champs
foreach ($donnees as $nom => $valeur) {
    if (is_array($valeur)) {
        $valeur = implode(' ', $valeur);
    }
    if (preg_match('/https?:\/\/|www\./i', $valeur)) {
        $errors[] = 'Le champ "' . htmlspecialchars($nom) . '" contient un lien, ce qui est interdit.';
    }
}

// Vérification des erreurs
if (!empty($errors)) {
    if ($isAjax) {
        cfJsonResponse(['success' => false, 'error' => implode(' ', $errors), 'csrf_token' => $newCsrfToken]);
    }
    $ref = $_SERVER['HTTP_REFERER'] ?? ($siteUrl . '/');
    $sep = strpos($ref, '?') !== false ? '&' : '?';
    header('Location: ' . $ref . $sep . 'cf_error=' . urlencode(implode(' ', $errors)) . '&cf_form=' . $formId);
    exit;
}

// Store submission
try {
    $ip        = $_SERVER['REMOTE_ADDR'] ?? '';
    $userAgent = substr($_SERVER['HTTP_USER_AGENT'] ?? '', 0, 500);
    $stmt = $pdo->prepare("
        INSERT INTO contact_form_submissions (form_id, donnees, ip_address, user_agent)
        VALUES (?, ?, ?, ?)
    ");
    $stmt->execute([$formId, json_encode($donnees, JSON_UNESCAPED_UNICODE), $ip, $userAgent]);
} catch (Exception $e) {
    error_log('contact-form-submit.php DB error: ' . $e->getMessage());
}

// Optional: send email notification
if (!empty($form['email_dest'])) {
    try {
        require_once __DIR__ . '/includes/mail-templates.php';
        require_once __DIR__ . '/includes/functions.php';

        // Resolve {{company}} from config / parametres
        $companyName = $config['COMPANY_NAME'] ?? '';
        if (empty($companyName)) {
            try {
                $stmtC = $pdo->prepare("SELECT valeur FROM parametres WHERE cle = 'nom_societe' LIMIT 1");
                $stmtC->execute();
                $row = $stmtC->fetch(PDO::FETCH_ASSOC);
                $companyName = $row['valeur'] ?? '';
            } catch (Exception $e) {}
        }

        $customTemplate = trim($form['email_template'] ?? '');

        if ($customTemplate !== '') {
            // Build variable map: form fields + site variables
            $variables = array_merge(
                $donnees,
                [
                    'form_name' => $form['nom'],
                    'company'   => $companyName,
                ]
            );
            $bodyHtml = replaceTemplateVariables($customTemplate, $variables);
            // {{signature}} is handled by sendEmail() (defined in includes/mail-templates.php)
        } else {
            // Default template: simple list of submitted values
            $bodyLines = [];
            foreach ($donnees as $k => $v) {
                $bodyLines[] = '<strong>' . htmlspecialchars($k) . '</strong> : ' . htmlspecialchars(is_array($v) ? implode(', ', $v) : $v);
            }
            $bodyHtml = '<p>Nouvelle soumission du formulaire <strong>' . htmlspecialchars($form['nom']) . '</strong> :</p>'
                      . '<ul><li>' . implode('</li><li>', $bodyLines) . '</li></ul>';
        }

        sendEmail(
            $form['email_dest'],
            'Nouveau message — ' . $form['nom'],
            $bodyHtml
        );
    } catch (Exception $e) {
        error_log('contact-form-submit.php mail error: ' . $e->getMessage());
    }
}

// Confirmation message or redirect
$confirmationMsg = trim($form['message_confirmation'] ?? '');
if ($confirmationMsg === '') {
    $confirmationMsg = 'Votre message a bien été envoyé. Nous vous répondrons dans les plus brefs délais.';
}

if ($isAjax) {
    cfJsonResponse(['success' => true, 'message' => $confirmationMsg, 'csrf_token' => $newCsrfToken]);
}

$ref = $_SERVER['HTTP_REFERER'] ?? ($siteUrl . '/');
$sep = strpos($ref, '?') !== false ? '&' : '?';
header('Location: ' . $ref . $sep . 'cf_success=1&cf_form=' . $formId);
exit;
